name: frhodo
channels:
  - numba
  - cantera
  - conda-forge
  - defaults
dependencies:
  - cantera=2.5.1
  - ipopt=3.14.9
  - matplotlib=3.5.1
  - nlopt=2.7.1
  - numba=0.56.3
  - numpy=1.23.3
  - pip
  - pygmo=2.18.0
  - pyqt=5.12.3
  - qt=5.12.9
  - qtpy=1.11.2
  - requests=2.28.1
  - scipy=1.9.1
  - tabulate=0.9.0
  - pip:
    - dtcwt==0.12.0
    - rbfopt==4.2.4
